using PandaRedu.Domain.Entities.Abstractions;
using PandaRedu.Domain.Entities.Users.Identifiers;
using PandaRedu.Domain.Entities.Users.Primitives;
using PandaRedu.Domain.Guards;
using PandaRedu.Domain.Guards.Clauses;

namespace PandaRedu.Domain.Entities.Users.Models;

/// <summary>
/// <see cref="Credentials"/> entity representation that stores password and expiration information
/// for a <see cref="User"/>.
/// </summary>
public class Credentials : Entity<CredentialsId>, IExpireable
{
    /// <summary>
    /// Minimum allowed password length.
    /// </summary>
    public const int PasswordMinLength = 8;

    /// <summary>
    /// Number of months after which credentials expire.
    /// </summary>
    private const int ExpirationMonths = 1;

    /// <summary>
    /// Identifier of the <see cref="Credentials"/> entity.
    /// </summary>
    public sealed override CredentialsId Id { get; protected init; }

    /// <summary>
    /// Hashed password value container.
    /// </summary>
    public Password Password { get; private set; }

    /// <summary>
    /// Foreign key referencing the <see cref="Models.User"/> owning these credentials.
    /// </summary>
    public UserId UserId { get; private set; }

    /// <summary>
    /// Navigation property to the owner <see cref="Models.User"/>.
    /// </summary>
    public User User { get; private set; } = null!;

    /// <summary>
    /// Indicates whether the password was autogenerated (e.g., temporary password).
    /// </summary>
    public bool Autogenerated { get; private set; }

    /// <summary>
    /// UTC date/time when the credentials expire.
    /// </summary>
    public DateTime ExpiresAtUtc { get; private set; }

    /// <summary>
    /// True when the credentials are expired or were autogenerated (treated as expired).
    /// </summary>
    public bool IsExpired => Autogenerated || DateTime.UtcNow > ExpiresAtUtc;

    protected Credentials() { }

    private Credentials(CredentialsId id, Password password, UserId userId, bool autogenerated)
    {
        Id = id;
        Password = password;
        UserId = userId;
        Autogenerated = autogenerated;
        ExpiresAtUtc = DateTime.UtcNow.Date.AddMonths(ExpirationMonths);
    }

    /// <summary>
    /// Creates new <see cref="Credentials"/> entity.
    /// </summary>
    /// <param name="password">Password value wrapper</param>
    /// <param name="userId">Foreign key for the owning <see cref="Models.User"/></param>
    /// <param name="autogenerated">Whether the password was autogenerated</param>
    /// <returns>New <see cref="Credentials"/> entity</returns>
    public static Credentials Create (Password password, UserId userId, bool autogenerated)
    {
        Guard.For(userId).AgainstEmpty();
        Guard.For(password).AgainstEmpty();

        return new Credentials
        (
            id: CredentialsId.New(),
            password: password,
            userId: userId,
            autogenerated: autogenerated
        );
    }
}
