using LearnLink.Domain.Entities.Abstractions;
using LearnLink.Domain.Entities.Users.Identifiers;
using LearnLink.Domain.Entities.Users.Primitives;
using LearnLink.Domain.Guards;
using LearnLink.Domain.Guards.Clauses;

namespace LearnLink.Domain.Entities.Users.Models;

public class Credentials : Entity<CredentialsId>, IExpireable
{
    public const int PasswordMinLength = 8;
    private const int ExpirationMonths = 1;
    public sealed override CredentialsId Id { get; protected init; }
    public Password Password { get; private set; }
    public UserId UserId { get; private set; }
    public User User { get; private set; } = null!;

    public bool Autogenerated { get; private set; }
    public DateTime ExpiresAtUtc { get; private set; }
    public bool IsExpired => Autogenerated || DateTime.UtcNow > ExpiresAtUtc;

    protected Credentials() { }

    private Credentials(CredentialsId id, Password password, UserId userId, bool autogenerated)
    {
        Id = id;
        Password = password;
        UserId = userId;
        Autogenerated = autogenerated;
        ExpiresAtUtc = DateTime.UtcNow.Date.AddMonths(ExpirationMonths);
    }

    public static Credentials Create (Password password, UserId userId, bool autogenerated, DateTime? expiresAtUtc = null)
    {
        Guard.For(userId).AgainstEmpty();
        Guard.For(password).AgainstEmpty();

        return new Credentials
        (
            id: CredentialsId.New(),
            password: password,
            userId: userId,
            autogenerated: autogenerated
        );
    }
}
