using LearnLink.Domain.Entities.Users.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using LearnLink.Domain.Entities.Users.Identifiers;

namespace LearnLink.Adapter.Configurations;

internal sealed class CredentialsEntityTypeConfiguration : IEntityTypeConfiguration<Credentials>
{
    public void Configure(EntityTypeBuilder<Credentials> builder)
    {
        builder.HasKey(creds => creds.Id);

        builder
            .Property(creds => creds.Id)
            .HasConversion
            (
                credsId => credsId.Value,
                value => new CredentialsId(value)
            );

        builder
            .HasOne(creds => creds.User)
            .WithOne()
            .HasForeignKey<Credentials>(creds => creds.UserId)
            .IsRequired(true);

        builder
            .ComplexProperty(creds => creds.Password, builder =>
            {
                builder.Property(creds => creds.Salt).HasColumnName("Salt");
                builder.Property(creds => creds.Hash).HasColumnName("Hash");
            });

        builder
            .Property(creds => creds.Autogenerated)
            .IsRequired();
    }
}
